### ISSUE TITLE
ENV not being set to expected values

### ISSUE THREAD

**Issue by lifeiscontent** [nickjj/orats#21]
Hi there,

I just started using orats, great project, thanks for the hard work!

I was trying to install rspec and was wondering why my RAILS_ENV were being set to development when running tests.

I actually think that it is running in test, but when the dependencies that are being defined in groups within the gemfile, its still set to development such as:

```
group :test do
  gem 'shoulda-matchers', '~> 3.1'
end
```

then when I try to run a test with shoulda matchers, it says "Shoulda" is undefined, because the env that is being used is development.

Any help on this would be greatly appreciated. Thanks!

**Comment by nickjj** [comment]
Hi, and thanks.

When gems are in `group :test`, that just means they only get installed in that specific environment. It doesn't set your rails env to that group.

Have you tested your set up without orats?

It sounds to me like you need to run `docker-compose up --build` because you added a new gem. You still need to install it. Without Docker after adding that gem you would have ran `bundle install`. The build command above is going to do the same thing because eventually it'll hit the point in the Dockerfile where it bundle installs.

**Comment by nickjj** [comment]
Hi,

I'm closing this because there's been many months of inactivity. Feel free to re-open if you have additional feedback.
